// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Part__02_Inheritance;

#nullable disable

namespace Part__02_Inheritance.Migrations
{
    [DbContext(typeof(InheritanceDbContext))]
    partial class InheritanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Part__02_Inheritance.models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Part__02_Inheritance.models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("Part__02_Inheritance.models.Employee");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.ToTable("FullTimeEmployees", (string)null);
                });

            modelBuilder.Entity("Part__02_Inheritance.models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("Part__02_Inheritance.models.Employee");

                    b.Property<int>("CountOfHours")
                        .HasColumnType("int");

                    b.Property<decimal>("HourRate")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("PartTimeEmployees", (string)null);
                });

            modelBuilder.Entity("Part__02_Inheritance.models.FullTimeEmployee", b =>
                {
                    b.HasOne("Part__02_Inheritance.models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Part__02_Inheritance.models.FullTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Part__02_Inheritance.models.PartTimeEmployee", b =>
                {
                    b.HasOne("Part__02_Inheritance.models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Part__02_Inheritance.models.PartTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
